USE [Piramida2000]
GO

/****** Object:  StoredProcedure [dbo].[SP_ADD_DATA]    Script Date: 16.05.2017 14:02:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_ADD_DATA] 
(
	@PARNUMBER INTEGER,
	@DATA_DATE DATETIME,
	@OBJECT INTEGER,
	@ITEM INTEGER,
	@OBJTYPE INTEGER,
	@VALUE0 FLOAT,
	@VALUE1 FLOAT,
	@P2KSTATUS INTEGER,
	@P2KSTATUSH INTEGER,
	@RCVSTAMP DATETIME,
	@NOT_UPDATE INTEGER = 0,
	@APPID INTEGER = 0
) AS
	SET @RCVSTAMP = GETDATE()
	DECLARE @SEASON INTEGER
	SET @SEASON = 4023 -- Лето 2011 
	IF EXISTS(SELECT PARNUMBER FROM DATA WHERE PARNUMBER = @PARNUMBER AND
			DATA_DATE = @DATA_DATE AND SEASON = @SEASON AND OBJECT = @OBJECT AND
			ITEM = @ITEM AND OBJTYPE = @OBJTYPE)
	BEGIN
		IF (@NOT_UPDATE IS NULL) OR (@NOT_UPDATE = 0)
			UPDATE DATA WITH(UPDLOCK) SET VALUE0 = @VALUE0, VALUE1 = @VALUE1,
				P2KSTATUS = @P2KSTATUS, P2KSTATUSH = @P2KSTATUSH, RCVSTAMP = @RCVSTAMP, APPID = @APPID
			WHERE PARNUMBER = @PARNUMBER AND DATA_DATE = @DATA_DATE AND SEASON = @SEASON AND
				OBJECT = @OBJECT AND ITEM = @ITEM AND OBJTYPE = @OBJTYPE
	END
	ELSE 
		INSERT INTO DATA (PARNUMBER, DATA_DATE, SEASON, OBJECT, ITEM, OBJTYPE,
			VALUE0, VALUE1, P2KSTATUS, P2KSTATUSH, RCVSTAMP, APPID)
		VALUES (@PARNUMBER, @DATA_DATE, @SEASON, @OBJECT, @ITEM, @OBJTYPE, @VALUE0,
			@VALUE1, @P2KSTATUS, @P2KSTATUSH, @RCVSTAMP, @APPID)


GO

